[build]
target = "../specs/avr-atmega328p.json"
rustflags = ["-C", "target-cpu=atmega328p"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -P /dev/ttyUSB0 -cb 57600"

[unstable]
build-std = ["core"]
